"""Set each face's name in that face, in the picker.

A list of forty-one typefaces written in one typeface tells you nothing
about any of them.  Written in themselves the list *is* the specimen: you pick
Fraktur because the word Fraktur is sitting there in blackletter, not because
you read the note underneath.

The whole trick is that a face only ever has to spell its own name here, so
that is all of it that ships.  Each TTF is subset to the couple of dozen
characters in its own label, turned into woff2 and written into the page as a
data URI -- forty-one faces come to about 130 KB that way, against 5.3 MB for
the files themselves, and nothing new has to be served: public/index.html is a
static file on Vercel and stays one.

Two adjustments keep the list a list rather than a ransom note.  `size-adjust`
scales each face so its capitals match the UI font's, because Bebas Neue and
Alfa Slab One set at the same pixel size are not the same size to look at.
`ascent-override` and friends pin every row to the same height, so a face with
tall accents does not push its neighbours around.

    python3 src/gen_specimens.py          # rewrites the block in index.html
    python3 src/gen_specimens.py --check  # fails if the block is out of date

The block is generated, and between markers that say so.  Re-run it after
adding a face to typefaces.FACES or changing a label.  It needs `brotli` for
the woff2 encoder, which is a build-time dependency and deliberately not in
requirements.txt -- the hosted function never runs this.
"""
import base64
import io
import re
import sys
from pathlib import Path

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

import cards
import typefaces

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "public" / "index.html"

OPEN = "  /* ---- face specimens: generated by src/gen_specimens.py ---- */"
CLOSE = "  /* ---- end face specimens ---- */"

# Inter's capitals, as a fraction of its em.  Every face is scaled so its own
# capitals come out this tall, which is what makes the list look like one list.
UI_CAP = 0.727
UI_STACK = 'Inter, "Inter Variable", system-ui, sans-serif'

# The line every row sits on, in fractions of the em.  Held the same for all of
# them: a face is welcome to look like anything, but not to change the row
# height and shove the rest of the list down.
ASCENT, DESCENT, GAP = 88, 22, 0

# Nothing here needs to be bigger than its own name, and a face that scaled
# past this would tower over the list.
SIZE_MIN, SIZE_MAX = 60, 160


def specimen(path, text):
    """`path` subset to the characters of `text`, as woff2 bytes.

    `recalcTimestamp=False` is what makes this reproducible.  fontTools stamps
    head.modified with the time of the save unless told not to, so the same
    font subset to the same string comes out a different 4 KB every run, and
    the generated block below would be a fresh 130 KB of churn in every diff
    whether or not a single letter had changed.
    """
    font = TTFont(path, recalcTimestamp=False)
    opt = Options()
    opt.notdef_outline = False
    # Concatenate rather than +=, which would extend the list in place and
    # leak FFTM into every later Options() in the process.
    opt.drop_tables = list(opt.drop_tables) + ["FFTM"]   # FontForge's, unsubsettable
    sub = Subsetter(options=opt)
    sub.populate(text=text)
    sub.subset(font)
    font.flavor = "woff2"
    out = io.BytesIO()
    font.save(out)
    return out.getvalue()


def block():
    """The whole generated stylesheet, markers included."""
    lines = [OPEN,
             "  /* Each face subset to the characters of its own label, so the",
             "     picker is its own specimen sheet.  Do not edit by hand. */"]
    rules, total = [], 0
    for key, spec in typefaces.FACES.items():
        path = typefaces.face(key)["path"]
        label = f"{spec['label']} — {spec['font']}"
        data = specimen(path, label)
        total += len(data)
        # Match this face's capitals to the UI font's.
        size = round(UI_CAP / cards.cap_per_em(path) * 100)
        size = max(SIZE_MIN, min(SIZE_MAX, size))
        b64 = base64.b64encode(data).decode("ascii")
        lines.append(
            f'  @font-face {{ font-family: "sp-{key}"; font-display: swap;'
            f' size-adjust: {size}%; ascent-override: {ASCENT}%;'
            f' descent-override: {DESCENT}%; line-gap-override: {GAP}%;'
            f' src: url(data:font/woff2;base64,{b64}) format("woff2"); }}')
        # The option in the open list, and the control itself once it is shut:
        # a native <select> hands its popup to the platform on Safari and on
        # both phones, and the option rule is quietly ignored there.  The
        # data-face rule is not, so the face you chose is set in itself
        # wherever you are, and the list follows suit where the browser allows.
        rules.append(f'  #font option[value="{key}"], #font[data-face="{key}"]'
                     f' {{ font-family: "sp-{key}", {UI_STACK}; }}')
    lines += rules
    lines.append(f"  /* {len(typefaces.FACES)} faces, {total // 1024} KB of woff2 */")
    lines.append(CLOSE)
    return "\n".join(lines)


def write(check=False):
    page = PAGE.read_text()
    made = block()
    if OPEN in page:
        start = page.index(OPEN)
        end = page.index(CLOSE) + len(CLOSE)
        now = page[start:end]
        page = page[:start] + made + page[end:]
    else:
        now = None
        anchor = page.index("</style>")
        page = page[:anchor] + made + "\n" + page[anchor:]
    if check:
        ok = now == made
        print("specimens are up to date" if ok else
              "specimens are STALE -- run python3 src/gen_specimens.py")
        return 0 if ok else 1
    PAGE.write_text(page)
    print(f"wrote {len(made) // 1024} KB of specimen CSS into {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(write(check="--check" in sys.argv[1:]))
